language: php
cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - SYMFONY_REQUIRE="4.4.*"
  - SYMFONY_REQUIRE="5.2.*"

matrix:
  include:
    - php: 7.1
      env:
        - SYMFONY_REQUIRE="4.4.*"
        - SOLARIUM_REQUIRE="^5.2"
        - CS_FIXER=1

    - php: 8.0
      env:
        - SYMFONY_REQUIRE="6.0.*"
        - STABILITY=dev

before_install:
    - phpenv config-rm xdebug.ini || echo "xDebug not disabled"
    - composer global require --no-progress --no-scripts --no-plugins symfony/flex

install:
  - rm -rf composer.lock vendor/*
  - if [[ ${STABILITY} ]]; then composer config minimum-stability ${STABILITY}; fi;
  - if [[ ${SOLARIUM_REQUIRE} ]]; then composer req solarium/solarium $SOLARIUM_REQUIRE; fi
  - composer update --prefer-dist

script:
    - if [[ ${CS_FIXER} == "1" ]]; then make php_cs_fixer_check; fi
    - make build
