language: php
cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - SYMFONY_REQUIRE="4.4.*"
  - SYMFONY_REQUIRE="5.0.*"

matrix:
  include:
    - php: 7.1
      env:
        - SYMFONY_REQUIRE="4.4.*"

before_install:
    - phpenv config-rm xdebug.ini || echo "xDebug not disabled"
    - composer global require --no-progress --no-scripts --no-plugins symfony/flex

install:
  - rm -rf composer.lock vendor/*
  - composer update

script:
  - make build
